# Pull base image
FROM python:3.12.0

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code
RUN apt-get update

# Copy project
COPY ./matcher/ ./matcher/
ENV PYTHONPATH /code/matcher:$PYTHONPATH

# Install dependencies
COPY ./requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY ./entrypoints/tail_f.sh /code/

RUN chmod +x /code/tail_f.sh
ENTRYPOINT ["/code/tail_f.sh"]