FROM node:20.10.0
 
WORKDIR /code

COPY ./client/ /client_frontend/

RUN npm install
RUN npm install bootstrap
RUN npm install universal-cookie
RUN npm install react-router-dom
RUN npm install axios
RUN npm install react-bootstrap
RUN npm install js-cookie
RUN npm install react-router-dom

COPY ./entrypoints/tail_f.sh /code/

EXPOSE 5173
 
RUN chmod +x /code/tail_f.sh
ENTRYPOINT ["/code/tail_f.sh"]