# Generated by Django 4.2.13 on 2024-06-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
