# Generated by Django 5.0.6 on 2024-05-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='school',
            new_name='school_id',
        ),
    ]
