# Generated by Django 5.0.6 on 2024-05-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0002_rename_school_teacher_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='company',
            new_name='company_cif',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teacher_dni',
        ),
    ]
