# Generated by Django 5.0.6 on 2024-05-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0003_rename_company_student_company_cif_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='company_cif',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher_dni',
            new_name='teacher',
        ),
    ]
