# Generated by Django 5.0.6 on 2024-05-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0004_rename_company_cif_student_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
