# Generated by Django 5.0.6 on 2024-05-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0005_rename_company_student_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_type',
            new_name='id_type_id',
        ),
    ]
