# Generated by Django 5.0.6 on 2024-05-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0006_rename_id_type_user_id_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_type_id',
            new_name='id_type',
        ),
    ]
