# Generated by Django 5.0.6 on 2024-05-31 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0008_remove_student_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funciones.activity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funciones.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funciones.student')),
            ],
            options={
                'unique_together': {('student', 'activity', 'company')},
            },
        ),
    ]
