# Generated by Django 5.0.6 on 2024-05-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0009_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
