# Generated by Django 5.0.6 on 2024-05-31 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0010_delete_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funciones.company'),
        ),
    ]
