# Generated by Django 5.0.6 on 2024-06-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0011_alter_student_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='work_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funciones.activity'),
        ),
    ]
