# Generated by Django 5.0.6 on 2024-06-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0012_alter_company_work_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='company_id',
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funciones.company'),
        ),
    ]
