FROM node:20.10.0

COPY ./client/ /client/

WORKDIR /client/

RUN npm install
RUN npm install bootstrap
RUN npm install universal-cookie
RUN npm install react-router-dom
RUN npm install axios
RUN npm install react-bootstrap
RUN npm install js-cookie
RUN npm install react-router-dom

COPY ./entrypoints/tail_f.sh /

EXPOSE 5173

RUN chmod +x /tail_f.sh
ENTRYPOINT ["/tail_f.sh"]