# Generated by Django 4.2.13 on 2024-06-08 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTipoUsuario',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('EMPRESA', 'Empresa'), ('DOCENTE', 'Docente')], default='ESTUDIANTE')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
